name: CMake

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    
    strategy:
      fail-fast: true
      matrix:
        os: [windows-latest]
        build_type: [Debug, Release]
        architecture: [x86, x64]

    steps:
    - uses: actions/checkout@v4

    - name: Configure CMake
      run: cmake --preset ${{ runner.os }}-${{ matrix.architecture }}-${{ matrix.build_type }}

    - name: Build
      run: cmake --build --preset ${{ runner.os }}-${{ matrix.architecture }}-${{ matrix.build_type }} --config ${{ matrix.build_type }}
